services:
  minio-server:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
      - '9080:80'
    volumes:
      - 'minio_data:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123

  # minio-client:
  #   image: bitnami/minio-client:latest    
  #   command: 'mc alias set myminio http://minio-server:9000 admin admin'
  #   depends_on:
  #     - minio-server

volumes:
  minio_data:
    external: true
    name: s3files