network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses: [192.168.0.250/24]
      routes: 
        - to: default
          via: 192.168.0.1
          metric: 10
      nameservers:
        addresses: [192.168.0.1]
    eth1:
      dhcp4: no
      addresses: [192.168.1.35/24]
      routes: 
        - to: default
          via: 192.168.1.1
          metric: 20
      nameservers: 
        addresses: [192.168.1.1]
