proxy-groups:
  - name: AutoProxy
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - HK
      - JP
      - SG
      - TW
      - US
      - 🇭🇰 日用 专线 香港 [0.2]
      - 🇸🇬 日用 专线 狮城 [0.2]
      - 🇯🇵 日用 专线 日本 [0.2]
      - 🇺🇸 日用 专线 美国 [0.2]
      - 🇭🇰 高级 专线 香港 01
      - 🇭🇰 高级 专线 香港 02
      - 🇭🇰 高级 专线 香港 03
      - 🇭🇰 高级 专线 香港 04
      - 🇭🇰 高级 专线 香港 05
      - 🇭🇰 高级 专线 香港 06
      - 🇭🇰 高级 专线 香港 07
      - 🇭🇰 高级 专线 香港 08
      - 🇸🇬 高级 专线 狮城 01
      - 🇸🇬 高级 专线 狮城 02
      - 🇸🇬 高级 专线 狮城 03
      - 🇸🇬 高级 专线 狮城 04
      - 🇸🇬 高级 专线 狮城 05
      - 🇺🇸 高级 专线 美国 01
      - 🇺🇸 高级 专线 美国 02
      - 🇺🇸 高级 专线 美国 03
      - 🇺🇸 高级 专线 美国 04
      - 🇺🇸 高级 专线 美国 05
      - 🇺🇸 高级 专线 美国 06
      - 🇺🇸 高级 专线 美国 07
      - 🇺🇸 高级 专线 美国 08
      - 🇺🇸 高级 专线 美国 09
      - 🇺🇸 高级 专线 美国 10
      - 🇰🇷 高级 专线 韩国 01
      - 🇰🇷 高级 专线 韩国 02
      - 🇨🇳 高级 专线 台湾 01
      - 🇨🇳 高级 专线 台湾 02
      - 🇯🇵 高级 专线 日本 01
      - 🇯🇵 高级 专线 日本 02
      - 🇯🇵 高级 专线 日本 03
      - 🇯🇵 高级 专线 日本 04
      - 🇯🇵 高级 专线 日本 05
      - 🇯🇵 高级 专线 日本 06
      - 🇯🇵 高级 专线 日本 07
      - 🇯🇵 高级 专线 日本 08
      - 🇭🇰 标准 专线 香港 01
      - 🇭🇰 标准 专线 香港 02
      - 🇭🇰 标准 专线 香港 03
      - 🇸🇬 标准 专线 狮城 01
      - 🇸🇬 标准 专线 狮城 02
      - 🇸🇬 标准 专线 狮城 03
      - 🇺🇸 标准 专线 美国 01
      - 🇺🇸 标准 专线 美国 02
      - 🇺🇸 标准 专线 美国 03
      - 🇺🇸 标准 专线 美国 04
      - 🇺🇸 标准 专线 美国 05
      - 🇺🇸 标准 专线 美国 06
      - 🇰🇷 标准 专线 韩国 01
      - 🇯🇵 标准 专线 日本 01
      - 🇯🇵 标准 专线 日本 02
      - 🇯🇵 标准 专线 日本 03
      - 🇯🇵 标准 专线 日本 04
      - 🇨🇳 标准 专线 台湾 01
      - 🇬🇧 特殊 专线 伦敦 01
      - 🇬🇧 特殊 专线 伦敦 02
      - 🇩🇪 特殊 专线 德国 01
      - 🇩🇪 特殊 专线 德国 02
      - 🇧🇷 特殊 专线 巴西 01
      - 🇧🇷 特殊 专线 巴西 02
      - 🇨🇦 特殊 专线 加拿大 01
      - 🇨🇦 特殊 专线 加拿大 02
      - 🇹🇷 特殊 专线 土耳其 01
      - 🇹🇷 特殊 专线 土耳其 02
      - 🇹🇭 特殊 专线 泰国
      - 🇻🇳 特殊 专线 越南
      - 🇮🇳 特殊 专线 印度
      - 🇦🇺 特殊 专线 悉尼
      - 🇦🇪 特殊 专线 迪拜
      - 🇫🇷 特殊 专线 法国
      - 🇳🇱 特殊 专线 荷兰
      - 🇮🇩 特殊 专线 印尼
      - 🇿🇦 特殊 专线 南非
      - 🇪🇬 特殊 专线 埃及
      - 🇵🇭 特殊 专线 菲律宾
      - 🇮🇹 特殊 专线 意大利
      - 🇪🇸 特殊 专线 西班牙
      - 🇭🇺 特殊 专线 匈牙利
      - 🇮🇱 特殊 专线 以色列
      - 🇺🇦 特殊 专线 乌克兰
      - 🇷🇺 特殊 专线 俄罗斯
      - 🇲🇾 特殊 专线 马来西亚
      - 🇯🇵 特殊 专线 尼日利亚
      - 🇵🇰 特殊 专线 巴基斯坦
      - 🇲🇩 特殊 专线 摩尔多瓦
      - 🇦🇷 购物 专线 阿根廷
  - name: Final
    type: select
    proxies:
      - AutoProxy
      - Proxies
      - DIRECT